### PR TITLE
Sachinsom93/gosw1

### PR DESCRIPTION
**Pull request by sachinsom93**
#### Issue Number
ISSUE #6 

#### Describe the changes you've made
Created a home page for GFG student chapter.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
Need to add GFG logo

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by sachinsom93** [comment]
Let me know If I need to do any amendments.

**Review by ashish11chawda — CHANGES_REQUESTED** [review]
@sachinsom93 Buddy your design is great!
**Please do not change code in files other than files for your component**
- Please revert the changes you've made in the `App.js` file

There's some problem with your code

bug

See the blank portion on the right side of the screen, it is present in all kinds of devices
Can you please work on it and fix it!

**Comment by sachinsom93** [comment]
Ok @pixan198, I will fix it ASAP.

**Comment by sachinsom93** [comment]
I solved that problem of little padding aside, 
Please review again

### Add this in App.js to test

``` import React from 'react';
 import Homepage from './screens/Homepage'
 import './App.css';

function App() {
  return (
    <div className="App">
      <Homepage />
    </div>
  );
}

export default App;
```

**Review by ashish11chawda — CHANGES_REQUESTED** [review]
@sachinsom93 Great Work!
It is responsive on all devices now.

A final change now
The images get squeezed in smaller devices like these:
bug_image2
bug_image1

Can you also fix this before I merge your PR?

**Comment by sachinsom93** [comment]
@pixan198  HI, I made images responsive. Kindly review them again.

**Comment by sachinsom93** [comment]
Hi @pixan198, let me know if had to do any change more ??

**Comment by ashish11chawda** [comment]
Hey @sachinsom93 , Sorry for the delay.
I'm reviewing your code
Meanwhile can you please resolve your conflicts on files `package.json` and `package-lock.json`

**Comment by ashish11chawda** [comment]
@sachinsom93 Buddy, Yeah the Page looks good.
Please resolve the conflicts and then we can merge your PR. :tada: 
Thank you for your patience.

**Review by ashish11chawda — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by ashish11chawda** [comment]
@sachinsom93 
Congratulations on successfully merging your first PR in this project :tada:

**Comment by sachinsom93** [comment]
Thanks for merging @pixan198 ,

**Comment by sachinsom93** [comment]
but what LGTM means ?

**Pull request merged**
