### PR TITLE
Priyanshu official/GOSW10

### PR DESCRIPTION
**Pull request by Priyanshu-official**
#### Issue Number
ISSUE #29 

#### Describe the changes you've made
Link the components to the navigation bar
#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Priyanshu-official** [comment]
@AVS18 @nanda-mik I have made PR and Fixed the Conflict
 and sorry about before conflict file

**Comment by Priyanshu-official** [comment]
@pixan198 Let me know If need any Changes 
Also, I am not able to Push PR of GSOW31
I think Because this Is not merge yet That's why 

Screenshot from 2020-10-28 13-28-44


Let me know If I am Wrong
@AVS18

**Comment by ashish11chawda** [comment]
@Priyanshu-official 
This might be because
- either your fork is not even with the base branch
- or your local is not updated with your fork and your upstream

Follow this [link](https://stackoverflow.com/questions/620253/git-push-rejected), I hope it helps.

**Comment by Priyanshu-official** [comment]
@pixan198 What I have done deleted all folder and make a new clone 
because I used so many Command that's why hope I am doing Right :)

can you tell me When this will be merged or need any changes

**Comment by ashish11chawda** [comment]
@Priyanshu-official that's okay for now
But please find a solution for that problem too, it'll help you in future

Please give us some time
I'll update you by EOD

**Comment by Priyanshu-official** [comment]
@pixan198 Ya sure you can take the time I know many people also there who need Guidance
I will find well I am Working on that but before I have to complete one More Issue GOSW24 That's Why I choose to delete a file  and make a new one

**Comment by pixan198** [comment]
@Priyanshu-official Sure buddy at last we need the work to be done :)

There's some changes for your code
- In Rightnav.jsx file you've used `Link` for routes and using `Router` from express so here in your code, both can't work together
- To use `react-router-dom` you need to import `BrowserRouter` and wrap your `StyledRightNav` inside it
- Also the `import Router from express` is not needed so you can remove that

Rest everything is good ! 👍🏻

**Comment by Priyanshu-official** [comment]
@pixan198 you mean 
import {Link} from 'react-router-dom' instead of this I use this
import { BrowserRouter, Link} from 'react-router-dom'
and  wrap it  StyledRightNav
Right ??

Ya also One think I have use link and Route it using the route.js file pls check the file too
I think it will work Without using BrowserRoute
let me know If I am wrong and I will make changes

**Comment by ashish11chawda** [comment]
Hey @Priyanshu-official Please give me some more time
I think there's some problem in your code but I couldn't understand what is it, so that's why 😕 

Until then
Please update the `package.json` file by running `npm install --save react-router-dom` and,
Line 1,2 and 3 in RightNav.jsx file are repeating so please remove them

**Comment by Priyanshu-official** [comment]
@pixan198 ya sure I will do that

**Comment by Priyanshu-official** [comment]
@pixan198 done I have made changes

**Comment by Priyanshu-official** [comment]
@pixan198 hi I Was curious how this conflict come? When I did PR there is no Conflict

**Comment by ashish11chawda** [comment]
@Priyanshu-official You're working simultaneously on multiple issues so your PR #67 for issue #57 has already merged all your changes present in this PR
So, I guess I'll have to close this as your code is already merged

**Comment by Priyanshu-official** [comment]
@pixan198 Ok It's means in just One PR I have solved 2 issue 🤦😬😂
So this legendary situation will count ?🤔

BTW I will carefull from now onwards 🤗

**Comment by ashish11chawda** [comment]
Yeah @Priyanshu-official , that's what happened
I'll talk to the team, it will count

From next time, only make a PR when your previous one gets merged or approved, but you can work on new issues though

**Comment by Priyanshu-official** [comment]
Ya sure no problem

**Pull request closed without merging**
