### PR TITLE
Sachinsom93/gosw16

### PR DESCRIPTION
**Pull request by sachinsom93**
#### Issue Number
ISSUE #35 

#### Describe the changes you've made
form for event registration.
#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by sachinsom93** [comment]
### code for test: 
import React from "react";
import EventForm from './components/EventForm'

```
function App() {
  return (
    <>
      <EventForm />
    </>
  );
}
export default App;
```

**Comment by sachinsom93** [comment]
Hi @pixan198, I have done some changes in App.test.js, to write a test query, 
Now all the test cases passed but app build is still failing because of reasons 
1. Some problems in MemberBlock.is file 
2. Declaration of some variables in App.js that never used in App.is

**Comment by sachinsom93** [comment]
@pixan198 , If you don't want to change anything in App.test.js, I"ll revert them.

**Comment by sachinsom93** [comment]
@pixan198 @nanda-mik ,kindly let me know if I need to do any changes in design or I need to add any new input field in event registration form.

**Comment by ashish11chawda** [comment]
Thank you @sachinsom93 for App.test.js file

Design is great! 🙌🏻

You may ignore the tests for now
We will update the App.js file soon

**Comment by sachinsom93** [comment]
> Thank you @sachinsom93 for App.test.js file
> 
> Design is great! 🙌🏻
> 
> You've not updated the package.json file
> Please add formik also by running `npm install --save formik`
> 
> You may ignore the tests for now
> We will update the App.js file soon

OK, Do I need to revert the changes in App.test.js ?

**Comment by sachinsom93** [comment]
@pixan198, for merging, it's my fifth merged PR 😅.

**Comment by ashish11chawda** [comment]
@sachinsom93 No, it is not needed now

Congratulations 🎊🎉 on Successfully merging your 5th PR  :)

**Pull request merged**
