### PR TITLE
Priyanshu official/GOSW24

### PR DESCRIPTION
**Pull request by Priyanshu-official**
#### Issue Number
ISSUE #55 

#### Describe the changes you've made
Added  Email notification feature after submitting the contact us form

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
#### Additional context (OPTIONAL)
I have Use Emailjs Which gives us More Feature and Easy to Implement 
for Testing Create Id in Dashboard > [https://dashboard.emailjs.com/](https://dashboard.emailjs.com/)

Adding Img of testing 

Screenshot from 2020-10-29 13-19-16

Screenshot from 2020-10-29 13-19-24

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Priyanshu-official** [comment]
@AVS18  Pls Review This

**Comment by geekyaditya100** [comment]
Ok will check buddy

**Review by 07souravkunda — COMMENTED** [review]
Hi @Priyanshu-official ! EmailJS requires pricing.Can you set up an SMTP server with nodejs for email service.

**Comment by Priyanshu-official** [comment]
@07souravkunda Ok I will do that with nodejs

**Comment by Priyanshu-official** [comment]
@07souravkunda I am closing this I will Make new PR OF EMAIL
By implementation of NODEJS

**Pull request closed without merging**
