### PR TITLE
ISSUE #4

### PR DESCRIPTION
**Pull request by Tejaswika**
#### GOSW-4
ISSUE 4

#### Describe the changes you've made
Added UI for Committee Members section , also added the flip animation on the cards on hover 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
No unusual behaviour

#### Additional context (OPTIONAL)
image

#### Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Tejaswika** [comment]
Did I have done the PR  in the correct branch , please help me out.😕

**Review by 07souravkunda — COMMENTED** [review]
Hi @Tejaswika !
Good job design is good. Just some few changes.
Don't add style to the tags like html and h1,h1. Use classname instead, it may affect other components in future.
In mobile view place cards in center.

**Comment by Tejaswika** [comment]
Sure I will work on it!!

**Comment by Tejaswika** [comment]
Done the required changes ,please check

**Review by 07souravkunda — COMMENTED** [review]
Screenshot 2020-10-22 181718

Use #DCDCDC for backgrounds shown in the image. For the font use greenish color.

**Comment by Tejaswika** [comment]
Suree!!!!

**Comment by Tejaswika** [comment]
I have to replace the green label background to #DCDCDC this or have to change the  color of the white background

**Comment by 07souravkunda** [comment]
green label to #dcdcdc

**Comment by Tejaswika** [comment]
And the white background?? should I changed it also

**Comment by manav014** [comment]
I think you may edit the Description of this PR and change to issue number to somewhat like ISSUE #9

**Comment by 07souravkunda** [comment]
> And the white background?? should I changed it also

No white is okay

**Comment by 07souravkunda** [comment]
Also don't edit app.js

**Review by 07souravkunda — COMMENTED** [review]
Great work @Tejaswika . Everythings seems right to me.

**Comment by 07souravkunda** [comment]
Just resolve conflicts I will merge it.

**Comment by Tejaswika** [comment]
I am trying to

**Comment by Tejaswika** [comment]
Done sir!!

**Pull request merged**
