### PR TITLE
priyanshu-official/GOSW10

### PR DESCRIPTION
**Pull request by Priyanshu-official**
#### Issue Number
ISSUE #29 

#### Describe the changes you've made
Added GOSW10-Link the components to the navigation bar
#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Priyanshu-official** [comment]
@pixan198 Pls Review this

**Comment by nanda-mik** [comment]
@Priyanshu-official Instead of using `<Link to={"path"}>Home</Link>`, use routing in react to connect to the components.

**Comment by Priyanshu-official** [comment]
@nanda-mik Ok Thank you for the suggestion

**Comment by Priyanshu-official** [comment]
@nanda-mik Review this

**Comment by Priyanshu-official** [comment]
@nanda-mik how I should fix this conflict?? 
we have to put Link at the position of the anchor tab

**Comment by nanda-mik** [comment]
@Priyanshu-official routing is done!, nice. I am not getting your question, Can you explain it a bit what you want to ask?

**Comment by Priyanshu-official** [comment]
@nanda-mik I was asking about this conflict.
Now it can be merged Right?

**Comment by nanda-mik** [comment]
@Priyanshu-official There are some conflicts in RightNav.jsx which is not showing to me. You check it once and try to resolve. After that i can merge.

**Comment by Priyanshu-official** [comment]
@nanda-mik This conflict because i have changed the tag <a></a> to Link I think that's why it show Conflict
Screenshot from 2020-10-27 10-57-22

**Comment by Priyanshu-official** [comment]
@nanda-mik How I Should Fix this Conflicts I am also not able to understand

**Comment by praveenscience** [comment]
Hi @Priyanshu-official, since there are only two changes, can you do me a favour.

1. First, have this branch copied into another branch.
2. Check out to the development branch.
3. Update your `development` branch with the latest one from the remote.
4. Delete your original branch locally.
5. Create a new branch from locally updated development branch.
6. Cherry-Pick your changes and put it in this branch.
7. Push the changes to the same branch using force push. This will update this PR.
8. Tag @AVS18 to merge the changes.

```bash
git checkout -b priyanshu-official/29-backup
git checkout development
git pull upstream development
git branch -d priyanshu-official/29
git checkout -b priyanshu-official/29
git cherry-pick a929153ede9f39aca597033c77942090963f861d
git cherry-pick fa67f8b209968487b5a5ba33ee3166e7559cec41
git push -u -f origin priyanshu-official/29
```

**Comment by Priyanshu-official** [comment]
@praveenscience Thank you sir For helping me out

**Comment by praveenscience** [comment]
@Priyanshu-official If you're having any troubles, let me know.

**Comment by Priyanshu-official** [comment]
@praveenscience I follow steps and Stuck here pls help 
Screenshot from 2020-10-28 00-34-45

**Comment by praveenscience** [comment]
Your branch must be clean... How is it not clean?

**Comment by Priyanshu-official** [comment]
@praveenscience I follow the step But I think I did Mistake somewhere 
ya by mistake I use the add command somewhere.
I will try to fix and update you

**Comment by praveenscience** [comment]
@Priyanshu-official Let's also try to take this up in my Live Stream here: [Handling Merge Conflicts in Git: Live Hands-on Practical Workshop - YouTube](https://www.youtube.com/watch?v=NAWVQx0OsYI)

**Comment by Priyanshu-official** [comment]
@praveenscience ya Will we there
Let me know If i can do something

**Comment by Priyanshu-official** [comment]
@nanda-mik Where is the Navbar file 
I have checked development branch and main branch

**Pull request closed without merging**
