### PR TITLE
Added Google Firebase Authentication setup#33

### PR DESCRIPTION
**Pull request by Priyanshu-official**
#### Issue Number
#33 

#### Describe the changes you've made
Installed And Setup google firebase auth for login 
#### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA
#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Priyanshu-official** [comment]
@nanda-mik Pls Review if any Changes need pls Let me know 
and I have made Setup For auth.

**Comment by Priyanshu-official** [comment]
@pixan198 Pls review if you are free

**Comment by nanda-mik** [comment]
@Priyanshu-official it was under review please wait a bit!!

**Comment by Priyanshu-official** [comment]
@nanda-mik ok

**Comment by Priyanshu-official** [comment]
@nanda-mik let me Know if have to add get element too..

**Comment by ashish11chawda** [comment]
Hey @Priyanshu-official 
Sorry for the delay from my side
Until @nanda-mik is reviewing your PR, Please resolve all the merge conflicts with your code

**Comment by Priyanshu-official** [comment]
@pixan198 Thank you reply
I am also not able to understand the conflict. can you help me to find when you have time 
till then I am trying to find.

**Comment by ashish11chawda** [comment]
Yeah @Priyanshu-official 

For the index.js file you don't need to change anything as I see the code
And for the App.js file, can we have a seperate component which deals with sign in and sign up only
I mean it would be good right?

**Comment by Priyanshu-official** [comment]
@pixan198 Ok you are right 
I will do it!

**Pull request closed without merging**
