### PR TITLE
Created a Signup Form

### PR DESCRIPTION
**Pull request by amisha64**
#### Issue Number
ISSUE #32

#### Describe the changes you've made
Created an interactive & fully responsive signup form along with proper validation for password, etc for new users.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by nanda-mik** [comment]
@amisha64 give the signup form some good styling and also some good css to the password info which was above the box. 

Capture

**Comment by nanda-mik** [comment]
@amisha64 explore material-ui for better styling!

**Comment by amisha64** [comment]
> @amisha64 explore material-ui for better styling!

Okay..I will.

**Comment by nanda-mik** [comment]
@amisha64 is it done amisha?

**Comment by amisha64** [comment]
> @amisha64 is it done amisha?

Can I ask for few hours more? Till morning?

**Comment by geekyaditya100** [comment]
@amisha64 Update your status. I recommend the following things to be completed now ASAP.
1. The branch code you committed have some conflicts. Do one thing, take the latest code from development branch in GameofSource/Web-Dev. Use npm install in both client and server code
2. Add your additions along with the UI change
3. Make a new branch as amisha64/gosw13_rebuild and make a new pr
4. Add a screenshot of the final ui version

We will merge your PR as soon as possible

If you are not interested in taking this pr to be merged let us know at the earliest.

**Comment by amisha64** [comment]
> @amisha64 Update your status. I recommend the following things to be completed now ASAP.
> 
> 1. The branch code you committed have some conflicts. Do one thing, take the latest code from development branch in GameofSource/Web-Dev. Use npm install in both client and server code
> 2. Add your additions along with the UI change
> 3. Make a new branch as amisha64/gosw13_rebuild and make a new pr
> 4. Add a screenshot of the final ui version
> 
> We will merge your PR as soon as possible
> 
> If you are not interested in taking this pr to be merged let us know at the earliest.

Done...Do check.

**Comment by amisha64** [comment]
I don't know why it still has conflicts. I did as it was suggested.

**Pull request closed without merging**
