### PR TITLE
Added image slider to show past, present and upcoming events

### PR DESCRIPTION
**Pull request by lakshaybomotra**
ISSUE #31 

I added image slider which can be used to show past, present and upcoming events. It has infinite loop, uses keyboard arrows, and is autoplay.

### CODE REVIEW

**Comment by ashish11chawda** [comment]
Hey @lakshayb121 
UI UX is great 🙌 
But It is not responsive on mobile devices
Can you please work on that!

Also, you don't need to import your component in the App.js file can you please revert that also!

1fe0829d-42a3-4fad-8232-6d054d7c4c28-3000 apps codespaces githubusercontent com_(Galaxy S5)

**Comment by lakshaybomotra** [comment]
> Hey @lakshayb121
> UI UX is great 🙌
> But It is not responsive on mobile devices
> Can you please work on that!
> 
> Also, you don't need to import your component in the App.js file can you please revert that also!
> 
> 1fe0829d-42a3-4fad-8232-6d054d7c4c28-3000 apps codespaces githubusercontent com_(Galaxy S5)

Hey i have made it responsive and removed my import of component in App.js and i have created a new pull request please check that.

**Comment by ashish11chawda** [comment]
Sure @lakshayb121 
But why did you close this PR
You are not working on it?

**Comment by lakshaybomotra** [comment]
> Sure @lakshayb121 
> But why did you close this PR
> You are not working on it?

Was getting some error on updating this pr

**Pull request closed without merging**
