### PR TITLE
Priyanshu official/GSOW31

### PR DESCRIPTION
**Pull request by Priyanshu-official**
#### Issue Number
ISSUE #57 

#### Describe the changes you've made
Created a Responsive footer

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
#### Additional context (OPTIONAL)

Screenshot from 2020-10-27 17-05-16

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Priyanshu-official** [comment]
@nanda-mik Pls let me know When you are free.
I want to talk about this conflicting file

**Comment by nanda-mik** [comment]
@Priyanshu-official Yes i am trying to resolve those! wait for some time.

**Comment by Priyanshu-official** [comment]
@nanda-mik Ya sure No Problem 
and Sorry about these conflict now I am learning about conflict file hope this not occur in other PR
Also pls tell someone See GSOW10 It doesn't have any Conflict.

**Comment by nanda-mik** [comment]
@Priyanshu-official Now conflicts are resolved. I am merging the footer issue. From next PR, pull the latest code from development branch and then work on your issue. Good work and we appreciate your consistent contribution.

**Pull request merged**
