### PR TITLE
Harshal0902/GOSW3

### PR DESCRIPTION
**Pull request by Harshal0902**
#### Issue Number
ISSUE #8 

#### Describe the changes you've made
Added two different sections for Mission and Vision.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
3A
3B

#### Test plan (OPTIONAL)
NA

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Harshal0902** [comment]
@nanda-mik please review this, and let me know if nay changes required.

**Comment by nanda-mik** [comment]
@Harshal0902

**Make these changes:**
1. Don't change the App.js file, we will import your component and check.
2. You have not pushed the images which you have used in the MisVis.css file check it once.
3. Try to resolve the conflicts in package-lock.json and package.json.

**Comment by Harshal0902** [comment]
@nanda-mik I have put images in assets folder

**Comment by Harshal0902** [comment]
@nanda-mik now all tests are failing and in details it showing other codes

**Comment by Harshal0902** [comment]
And as soon as I import MisVis in App.js it pass all the checks

**Comment by nanda-mik** [comment]
@Harshal0902  
Change the code like this` background: url("../../assets/vision.png") no-repeat right;` and no need to change App.js if the test fails also.

**Comment by Harshal0902** [comment]
So @nanda-mik can I work on GSOW32 now?

**Comment by Harshal0902** [comment]
@nanda-mik do I need to change anything?

**Comment by nanda-mik** [comment]
@nanda-mik try to resolve the conflicts?

**Comment by Harshal0902** [comment]
@nanda-mik I am not able to find out the conflict. I haven't use any framework, so why its showing conflict in package.json and package-lock.json ?

**Comment by praveenscience** [comment]
@Harshal0902 The problem is in App and package files. I tried giving this info to another one. Can you check and resolve the same way?
https://github.com/GameofSource-GFG/Web-Development/pull/59#issuecomment-717369873

**Comment by Harshal0902** [comment]
@praveenscience So should I delete this branch and make a new branch again?

**Comment by praveenscience** [comment]
@Harshal0902 I guess that will be a better idea, but don't delete the branch yet. Create the changes on top of the latest code.

**Comment by Harshal0902** [comment]
@praveenscience Ok sir

**Pull request merged**
