### PR TITLE
Added Timeline

### PR DESCRIPTION
**Pull request by Priyanshu-official**
#13
-->

#### Describe the changes you've made
I have added Components Of Responsive Timeline UI For the homepage

#### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Priyanshu-official** [comment]
@pixan198

**Comment by ashish11chawda** [comment]
@Priyanshu-official 
Your design is amazing 🌟
But it is not responsive, can you please work on that too?

Also don't change index.js file 
You just have to implement the component

**Comment by Priyanshu-official** [comment]
ok I will work on that
thanks for feedback
@pixan198

**Comment by Priyanshu-official** [comment]
@pixan198 Hi Review 
I have added a Responsive timeline
If need Any changes let me know

**Review by ashish11chawda — APPROVED** [review]
@Priyanshu-official Great Work buddy! :tada: 
It is responsive and works fine on all the screens

**Comment by Priyanshu-official** [comment]
@pixan198 Thank you Now I can Work on other projects Right?
When this will be Merged?

**Pull request merged**
