### PR TITLE
Priyanshu official/33

### PR DESCRIPTION
**Pull request by Priyanshu-official**
#### Issue Number
ISSUE #33

#### Describe the changes you've made
#41 Updated and made a component of a firebase in the component folder
#### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Priyanshu-official** [comment]
@pixan198 Pls review this I made Component only 
Now it's again show conflict

**Comment by ashish11chawda** [comment]
Hey @Priyanshu-official 
Your package.json file is old please update it as we are using now

**Comment by Priyanshu-official** [comment]
@pixan198 ok

**Comment by Priyanshu-official** [comment]
@pixan198 I have to try to update but see it still show conflict.
I have a fix the package.json file 

can you help me for updating the conflict file

**Comment by geekyaditya100** [comment]
@Priyanshu-official check it is still showing conflicts

**Comment by Priyanshu-official** [comment]
@geekyaditya100 yes I am doing the same can you pls check the package.jason file what conflict is there I have fixed

**Comment by Priyanshu-official** [comment]
@nanda-mik Fixed all conflicts :100:

**Comment by Priyanshu-official** [comment]
@pixan198 can you check this Please

**Review by nanda-mik — COMMENTED** [review]
why you created another function App() inside firebase.js ?

**Comment by nanda-mik** [comment]
@Priyanshu-official resolve the conflicts again and just make the firebase setup inside firebase.js. No need to create a function app you can export the firebase.auth() and import it in login. Use comments in your code for better explanation.

**Comment by Priyanshu-official** [comment]
@nanda-mik Ok Let me see

**Comment by Priyanshu-official** [comment]
@nanda-mik Review pls

**Comment by nanda-mik** [comment]
@Priyanshu-official Nice great work!!

**Comment by Priyanshu-official** [comment]
@nanda-mik Thanks 
thank for your effort and time for review

**Pull request merged**
