### PR TITLE
Sachinsom93/gosw9

### PR DESCRIPTION
**Pull request by sachinsom93**
#### Issue Number
ISSUE #14 

#### Describe the changes you've made
Created a responsive and fixed navigation.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by sachinsom93** [comment]
use this code in App.js to test :
```
import React from 'react';
import logo from './logo.svg';
import './App.css';
import Navbar from './components/Navbar/Navbar';

function App() {
  return (
    <div className="App">
      <Navbar />
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <h1>GameOfSource</h1>
      </header>
    </div>
  );
}

export default App;

```

**Comment by geekyaditya100** [comment]
Hi @sachinsom93  can you check the package-lock.json it is showing some conflict errors

**Comment by sachinsom93** [comment]
> Hi @sachinsom93 can you check the package-lock.json it is showing some conflict errors

OK, other then this do I need to do any change regarding design or responsiveness @geekyaditya100 ?

**Comment by sachinsom93** [comment]
@geekyaditya100 , now conflicts are resolved.

**Pull request merged**
