### PR TITLE
Somashrirastogi/gosw 5

### PR DESCRIPTION
**Pull request by somashrirastogi**
#### Issue Number
ISSUE #
#5
Example:
ISSUE #5
-->

#### Describe the changes you've made
I had created the Contact Us page with Name, email, contact no. and message text field. If there are any changes to be made please let me know

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA
Screenshot (152)

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by somashrirastogi** [comment]
Please let me know for any amendments to be made in this.

**Review by 07souravkunda — COMMENTED** [review]
@somashrirastogi use css modules stylesheet. This type of css can affect styles of other components. Place all the .module.css files inside Contact-Us folder. Add some paddings and change fontsize for mobile view.

**Comment by somashrirastogi** [comment]
Ok sir

**Review by 07souravkunda — COMMENTED** [review]
Don't edit app.js. Rest is fine.

**Comment by somashrirastogi** [comment]
> Don't edit app.js. Rest is fine.

Done sir.

**Comment by somashrirastogi** [comment]
Screenshot (154)
Updated submit button.

**Comment by eshanvohra** [comment]
hi, pls center the submit button.
~make .sub in ContactUs.css to 
.sub {
     background-color: #71AC15 ;
     color: white;
     font-size: 20px;
     padding-top: 0px;
     padding: 10px 30px;
     border: none;
     border-radius: 4px;
     cursor: pointer;
     display: flex;
     margin:0px auto;
     font-weight: 600;
}

**Comment by somashrirastogi** [comment]
@eshanvohra Done.

**Comment by eshanvohra** [comment]
ok seen wait i'll inform the maintainers

**Comment by 07souravkunda** [comment]
Great work @somashrirastogi .Just resolve the conflicts. I will merge it.

**Comment by somashrirastogi** [comment]
> Great work @somashrirastogi .Just resolve the conflicts. I will merge it.

Thank You so much Sir.

**Pull request merged**
