### PR TITLE
Harshal0902/GOSW6

### PR DESCRIPTION
**Pull request by Harshal0902**
#### Issue Number 6
ISSUE #

#### Describe the changes you've made
Added a map showing location of Student Chapter. Please enter your own Google Map API to view the map.

#### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
No

#### Additional context (OPTIONAL)
6A

#### Test plan (OPTIONAL)
NA

#### Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Harshal0902** [comment]
Please tell me if any change recquired.

**Comment by Harshal0902** [comment]
@pixan198 Can you please review this.

**Comment by ashish11chawda** [comment]
Hey @Harshal0902 
Sorry for the delay
#### Problems in your code:
- Your build is failing please see that
> I think it is because you've not updated your package.json file, please see that

- You've changed the App.js file you've to never do that unless told to do so

### Changes you've to make:
- Make a component for the map inside the components folder
- Put your code inside in a file
- Revert all the changes you've made to the App.js file

**Comment by Harshal0902** [comment]
@pixan198 done, Can you please review it.

**Comment by ashish11chawda** [comment]
Hey @Harshal0902 there are still merge conflicts with your PR
Please resolve it

So, you don't have to import the component as of now in App.js and revert the changes you've made in the App.js file

**Comment by Harshal0902** [comment]
@pixan198 is this fine now

**Comment by ashish11chawda** [comment]
Hey @Harshal0902 
I've fixed the App.js file

Why you've deleted all components which were present in the components folder
You don't have to delete anything

Please restore all the components as they were
- AboutUs
- Committee
- Homepage
- Contact-us
- Timeline

I may have missed something but please restore all components as they were before

**Comment by Harshal0902** [comment]
@pixan198 done, can you please review it

**Comment by Harshal0902** [comment]
@pixan198 please review this

**Comment by ashish11chawda** [comment]
Yeah @Harshal0902 

#### Your checks are failing because of few things:
- you've not updated the `package.json` as you're using axios. So try running `npm install --save axios` in your terminal inside `client/` directory
- You've named your files as Map.js please rename it to something like GMap.js or whatever suitable you prefer
- inside your Map.js file at export statement, replace Map with App

I think this should fix it

And the result looks good to me!
Please fix this then we can merge your Pull Request
Your commit should pass all the checks!

**Comment by Harshal0902** [comment]
@pixan198 I did as you told me, but still this is showing all check failed and in details its showing someone else code

**Comment by ashish11chawda** [comment]
Don't worry @Harshal0902 It is not because of your code
I'll soon merge your PR

**Comment by Harshal0902** [comment]
@pixan198 Thanks a lot, for helping me out.

**Comment by ashish11chawda** [comment]
You're welcome @Harshal0902 

Congratulations on Successfully merging your Pull Request 🎉🎉

Don't forget to update your PR count and fill the form.

**Pull request merged**
