### PR TITLE
added Timeline

### PR DESCRIPTION
**Pull request by Priyanshu-official**
Added Timeline #13

### CODE REVIEW

**Comment by Priyanshu-official** [comment]
@pixan198 Pls Review 
if any changes need let me Know.

**Review by ashish11chawda — CHANGES_REQUESTED** [review]
@Priyanshu-official Buddy we are working on React and you've wrote HTML code

Can you please convert this into a React Component
Also follow the project's folder structure, you need to keep your components inside client/src/

Please let me know if you've any doubts

**Comment by Priyanshu-official** [comment]
@pixan198 Ohh Ok 
I will do it 
sorry about that

**Comment by ashish11chawda** [comment]
@Priyanshu-official No problem buddy

UI is great BTW 🌟🌟

**Change one more thing**

You've to make Pull Request from your branch to `development` branch of our repo, so change the base branch from `main` to `development`

**Comment by Priyanshu-official** [comment]
ok And thanks
@pixan198

**Comment by Priyanshu-official** [comment]
@pixan198 Hello need help
I have converted to React and tested work fine
but just want to ask I have created a file in src/
The question is: is it Right or I have to create a folder??
also, I have linked to index.js 
pls If you have time reply so i can make pr

**Comment by ashish11chawda** [comment]
@Priyanshu-official Great !

Usually components are placed inside
`src/components/` directory
So, you can place your component there

**Comment by Priyanshu-official** [comment]
@pixan198 yes but there are no Components folder
Can I make it??

**Comment by ashish11chawda** [comment]
@Priyanshu-official 
Yes!
If there isn't any you can create one

**Comment by Priyanshu-official** [comment]
Ok thanks for help

**Comment by Priyanshu-official** [comment]
@pixan198 I have made PR in Development  branch check pls
I have change branch for the first time while working Pls check if I did wrong

**Comment by ashish11chawda** [comment]
@Priyanshu-official 
Branch is correct 👍🏻
Please give us some time to review your PR
Thank you

**Comment by Priyanshu-official** [comment]
@pixan198 No Problem 
I was just Worry about the branch Now Happy is it good
Can you tell me How much PR needs to be done with any Specific limit?
also, there is no new issue?

and Thanks for helping me

**Comment by ashish11chawda** [comment]
@Priyanshu-official yeah, branch is fine.
Make as much PRs as you want

We'll be releasing new issues soon

Thank you for being patient

**Pull request closed without merging**
