### PR TITLE
Harshal0902/gosw32

### PR DESCRIPTION
**Pull request by Harshal0902**
#### Issue Number
ISSUE #58 

#### Describe the changes you've made
Added a scroll to top button.
#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
32 A

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Harshal0902** [comment]
@nanda-mik @geekyaditya100 please let me know, if any changes required

**Comment by AVS18** [comment]
Yeah its good. Try to resolve the merge conflicts.

**Comment by Harshal0902** [comment]
@AVS18 I am not getting how to resolve conflicts.

**Comment by Harshal0902** [comment]
@AVS18 can I work on another issue?

**Comment by manav014** [comment]
Hey @Harshal0902  Please do one thing, remove the package-lock.json from the Pull Request. I will update the same manually, I have copied your package-lock.json file code. Please update me once done so that I may merge

**Comment by Harshal0902** [comment]
@manav014 done

**Comment by Harshal0902** [comment]
@manav014 now all tests are failing, should I add it again?

**Comment by manav014** [comment]
Yeah just add it as checks are to be verified and also now I will tell you the line which is conflicting within a few minutes after adding it again.

**Comment by Harshal0902** [comment]
@manav014 Done

**Comment by Harshal0902** [comment]
So @manav014 can i work on other issue now?

**Comment by manav014** [comment]
Yeah! I am working on it and will update you with the solution.

**Comment by Harshal0902** [comment]
So right now can I work on new issue or not?

**Comment by manav014** [comment]
Yes you may.

**Comment by manav014** [comment]
But please keep the solution, i would be proposing, on priority in future for this issue.
Thank You

**Comment by manav014** [comment]
@Harshal0902 Please use `git pull upstream main` in the GOSW32 branch and update it with the project main branch as it is not updated with the main branch. Please do the same on a priority basis.

**Comment by Harshal0902** [comment]
@manav014 done. Bu it is showin 
$ git pull upstream main
From https://github.com/GameofSource-GFG/Web-Development
 * branch            main       -> FETCH_HEAD
Already up to date.

**Comment by Harshal0902** [comment]
@manav014 can you please assign issue GOSW25 to me?

**Comment by manav014** [comment]
I pushed your changes in the main branch manually as the reason of conflict was unknown. So this PR would be graded and considered as merged. I am closing it.

**Comment by Harshal0902** [comment]
Thank a lot @manav014 for helping me out. Cay you please assign issue GOSW25 to me?

**Pull request closed without merging**
