### PR TITLE
Harshal0902/GOSW15

### PR DESCRIPTION
**Pull request by Harshal0902**
#### Issue Number
ISSUE #34 

#### Describe the changes you've made
Added a 2 factor authentication for users and made the validation request to the users.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Please enter your Firebase Authentication Details in Config.js file

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Harshal0902** [comment]
@geekyaditya100 please review this and let me know any changes.

**Comment by nanda-mik** [comment]
@Harshal0902 Can you explain your approach for your 2 factor auth setup? Have you used the verification code to user's phone method or something else? Use comments for proper explanation and resolve the conflicts. 
Your work is great but you have to go along with others. You have made your own login, signup and config again. Login signup pages and firebase auth setup are in other issues. You try to collaborate with others and if some part is not completed, then wait for that issue to be completed and merged then you start your work no need to worry about time, then it will be easier to integrate!!

**Comment by Harshal0902** [comment]
@nanda-mik Sign Up page issue is not yet completed, so can I continue my work when the page got build.

**Comment by nanda-mik** [comment]
@Harshal0902 Yes wait for them to complete.

**Comment by praveenscience** [comment]
@AVS18 Please go ahead and merge this, it has been resolved.

**Comment by geekyaditya100** [comment]
@Harshal0902  Thank you for the contribution. We have merged your pull request. You have received 10 points for the contribution.

**Comment by Harshal0902** [comment]
@geekyaditya100 @nanda-mik Thank a lot for helping me out

**Pull request merged**
