### PR TITLE
Sachinsom93/gosw7

### PR DESCRIPTION
**Pull request by sachinsom93**
#### Issue Number
ISSUE #12 

#### Describe the changes you've made
Created a bar that contains all the social media hanles

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by sachinsom93** [comment]
### Use this code in App.js for test;
```
import React from 'react';
import logo from './logo.svg';
import './App.css';
import SocialMediaHandles from './componets/SocialMediaHandles';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <h1>GameOfSource</h1>
      </header>
      <SocialMediaHandles />
    </div>
  );
}

export default App;

```

**Comment by nanda-mik** [comment]
@sachinsom93 put the SocialMediaHandle.jsx file inside components folder and import it to app.js. You have created another componets folder with a spelling mistake. Do the changes!!

**Comment by sachinsom93** [comment]
OK, I just need to rename that component folder , right ?

**Comment by sachinsom93** [comment]
> @sachinsom93 put the SocialMediaHandle.jsx file inside components folder and import it to app.js. You have created another componets folder with a spelling mistake. Do the changes!!

Done @nanda-mik , Please review it again.

**Comment by nanda-mik** [comment]
@sachinsom93 nice work!

**Pull request merged**
