### PR TITLE
Harshal0902/GOSW2

### PR DESCRIPTION
**Pull request by Harshal0902**
#### Issue Number
ISSUE 2

I have add an image and a short description at top. And the bottom I have added some features

There was no unusual behavior in my code

2A
2B

#### Checklist
Example how to mark a checkbox :-
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by ashish11chawda — CHANGES_REQUESTED** [review]
@Harshal0902 Great work on this component!
You need to do a few changes before we can merge this PR
- Do not change the code in files other than your code, as you've changed `src/App.css`, `src/App.js`, `src/index.js`, and `public/index.html`
> **Please revert these changes back to as they were**

- For importing a CSS file, you can import it in the component itself instead of the parent component, like you could do `import './Aboutus.css'` in `AboutUs.js` file

#### Great work on the design and its responsiveness :star2:

**Comment by Harshal0902** [comment]
@pixan198 I just have to import 'Aboutus.css' in AboutUs.js . Rest are correct right?

**Comment by ashish11chawda** [comment]
@Harshal0902 you've to import the css module and please revert the changes I've mentioned in above comment
Thank you

**Comment by Harshal0902** [comment]
Done, can you please check it.

**Comment by ashish11chawda** [comment]
@Harshal0902 
Please revert the changes you've made in the `client/src/index.js` file
Rest everything is fine

**Comment by Harshal0902** [comment]
@pixan198 is this all right?

**Comment by ashish11chawda** [comment]
@Harshal0902 yes it's fine

**Review by ashish11chawda — APPROVED** [review]
@Harshal0902 Great work! 🎉🌟
Congratulations on Successfully merging your first PR on this project.

**Comment by Harshal0902** [comment]
@pixan198 Thank a lot 😁😁

**Pull request merged**
